spring.application.name=telemetry-gateway
influxdb.url=${INFLUXDB_URL:http://localhost:8086}
influxdb.token=9YWTsBsTYOflp5qTxDx2hs9QXpoMHlbyNzngBiV3AEP6KQTXRG6lSRNMhPEYAV-l8hQp2jyM5FgO7yLUcDtXHw==
influxdb.org=${INFLUXDB_ORG:sim-racing}
influxdb.bucket=${INFLUXDB_BUCKET:assetto-corsa}
